server:
  port: ${OAUTH_INTERNAL_API_PORT:3001}

spring:
  application:
    name: oauth

management:
  server:
    port: ${OAUTH_INTERNAL_METRICS_PORT:9464}
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8081}
  realm: ${KEYCLOAK_REALM:constrsw}
  client-id: ${KEYCLOAK_CLIENT_ID:oauth}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:}
